2019-02-23 12:48:51,065 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:49]
2019-02-23 12:49:00,360 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:49]
2019-02-23 13:17:05,489 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:49]
2019-02-23 13:17:08,616 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:49]
2019-02-23 13:27:36,962 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:51]
2019-02-23 14:15:19,658 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:51]
2019-02-23 14:24:50,667 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:51]
2019-02-23 14:51:28,889 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:52]
2019-02-23 15:53:45,441 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:52]
2019-02-23 16:03:57,534 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:52]
2019-02-23 16:22:15,091 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:52]
2019-02-23 16:22:28,973 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:52]

2019-02-23 16:41:40,934 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:57]
2019-02-23 16:42:00,688 ERROR: Exception on /reset_password_request [POST] [in /Users/tberg/Documents/Dev/PyCharm/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/tberg/Documents/Dev/PyCharm/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tberg/Documents/Dev/PyCharm/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tberg/Documents/Dev/PyCharm/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/tberg/Documents/Dev/PyCharm/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/tberg/Documents/Dev/PyCharm/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tberg/Documents/Dev/PyCharm/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tberg/Documents/Dev/PyCharm/microblog/app/routes.py", line 179, in reset_password_request
    send_password_reset_email(user)
  File "/Users/tberg/Documents/Dev/PyCharm/microblog/app/email.py", line 26, in send_password_reset_email
    html_body=render_template('email/reset_password.txt', user=user, token=token))
  File "/Users/tberg/Documents/Dev/PyCharm/microblog/app/email.py", line 12, in send_email
    Thread(target=send_sync_email, args=(app, msg)).start()  # mail.send(msg)
NameError: name 'send_sync_email' is not defined
2019-02-23 18:25:09,850 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:57]
2019-02-23 18:26:38,829 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:57]
2019-02-23 18:33:40,146 INFO: Microblog startup [in /Users/tberg/Documents/Dev/PyCharm/microblog/app/__init__.py:56]
